sname=input("Enter the name of the student:")
sno=int(input("Enter the roll number of the student:"))
m=int(input("Enter the maths marks: "))
p=int(input("Enter the physics marks: "))
c=int(input("Enter the chemistry marks: "))
print("Details of the student are: ")
print("Name :",sname,"\nRoll Number :",sno,"\nMath marks: ",m,"\nPhysics marks: ",p,"\nChemistry marks: ",c)
print("Total marks: ",m+p+c)
print("Average marks: ",round((m+p+c)/3,2))